### ISSUE TITLE
Integration DB is not a good idea for relational DB?

### ISSUE THREAD

**Issue by joaonc** [mikeckennedy/mongodb-quickstart-course#10]
Howdy and thanks a ton for this course!   Ok, Q:

In the video here: https://training.talkpython.fm/player/course/mongodb-python-quickstart-mongoengine/lecture/100303

👉  _Integration DBs vs application DBs_, 1m13s, you say "an integration database isn't a great idea for relational databases."
Is that what you meant?   After the explanation a few seconds prior about the model being enforced by the applications and they could get out of sync, potentially getting to data corruption, I thought you were talking about *document* dbs, not relational dbs.

If a relational DB forces model at the DB level, won't that lead to *less* potential of data corruption?

<img width="1339" alt="for_relational_databases" src="https://user-images.githubusercontent.com/11450769/178367571-293731a0-fae3-4f80-bfe7-41c3f2c51acc.png">

**Comment by joaonc** [comment]
Text here: https://github.com/mikeckennedy/mongodb-quickstart-course/blob/ff89e4f9e86ffdf85c01e4cf400458017aa2d5de/video_transcripts/3-modeling-documents/3-integration-vs-app-dbs_transcript_final.txt#L29-L36

**Comment by mikeckennedy** [comment]
Hi @joaonc It does sound like I misspoke. Relational databases with their enforced structure and integrity are better than flexibly NoSQL DBs for integration databases.

**Comment by joaonc** [comment]
Got it, tx for the clarification.

**Suggestion:** To fix the video w/o re-creating or editing, add a feature similar to captions where text appears, say, on the top right of the screen. In this case (TR=Top Right):
```
start_time,duration,position,text
01:13,1,TR,"* document databases"
```

Thanks again for this course and the podcasts (I follow both your podcasts, but mainly listen to Python Bytes due to time).
This course is allowing me to evaluate using Mongo vs Postgres in a project we're about to start. Now playing around w/ Mongo and finding it super cool.
