### ISSUE TITLE
 No module named 'colorama'

### ISSUE THREAD

**Issue by jbrandes** [mikeckennedy/mongodb-quickstart-course#4]
I am trying to run your snakebnb course but it won't load past section 4 lecture nine due to this error:

ile "/home/jbrandes/mongodb-quickstart-course/src/snake_bnb/src/program.py", line 1, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

**Comment by mikeckennedy** [comment]
Hi,

There are a number of dependencies for this project (most notably pymongo for talking with MongoDB, but also colorama). To fix this, you'll need to install them via the command:

```pip3 install -r requirements.txt```

In the root folder. That'll fix it.
