### ISSUE TITLE
Where is the actual MongoDB - database to which you connect in the course?

### ISSUE THREAD

**Issue by AndreasLuckert** [mikeckennedy/mongodb-quickstart-course#9]
First of all, thanks for the [free course on Udemy](https://www.udemy.com/course/mongodb-and-python-quickstart-with-mongoengine)!

However, in section 5, video 16 you connect to the database, but in the github-files there is apparently no database to connect with.
At least I haven't found anything.
I've installed Robo 3T (formerly RoboMongo) to mimic what you're doing in the video, but where the database comes from is incomprehensible for me.

Thanks in advance for your help!

**Comment by mikeckennedy** [comment]
Hi @AndreasLuckert Can you share the title of the video you're talking about? The video I think you're talking about is just a concept video which doesn't have any data or code behind it.

The DB comes from just using the app and typing things into it BTW. In Mongo, you don't have to create the db with create scripts and whatnot.  That said, there is a data from what I typed during the course here:

https://github.com/mikeckennedy/mongodb-quickstart-course/tree/master/data
